# Generated by Django 5.0.3 on 2024-09-09 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_matricula'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Matricula',
        ),
    ]
