# Generated by Django 5.0.3 on 2024-09-09 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0004_matricula'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matricula',
            old_name='esdutante',
            new_name='estudante',
        ),
    ]
