# Generated by Django 5.0.3 on 2024-09-10 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0005_rename_esdutante_matricula_estudante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudante',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
